Repository ironcore-dev/FeDHCP, pull requests merged in 2024-06, with the labels that each got.

#151 Make PXE plugin not brake the plugin chain
  plugins/pxeboot/plugin.go
  plugins/pxeboot/plugin_test.go
Labels: enhancement, size/M

#152 Add address type check when selecting OOB networks
  plugins/oob/k8s.go
  plugins/oob/plugin.go
Labels: enhancement, size/S

#153 Always push
  .github/workflows/publish-docker.yml
Labels: size/XS

#140 Add netboot plugin
  main.go
  plugins/httpboot/plugin.go
Labels: size/L

#155 Adapt httpboot plugin to respond with client specific UKIs
  plugins/httpboot/plugin.go
Labels: size/L

#162 Add httpboot tests
  plugins/httpboot/plugin.go
  plugins/httpboot/plugin_test.go
Labels: enhancement, size/L
