Repository ironcore-dev/FeDHCP, pull requests merged in 2024-09, with the labels that each got.

#184 Bump golang to `v1.23`
  go.mod
  go.sum
Labels: size/L

#180 Add prefix delegation handling for `onmetal` plugin
  plugins/httpboot/plugin_test.go
  plugins/onmetal/plugin.go
  plugins/onmetal/plugin_test.go
Labels: documentation, enhancement, size/L

#186 Add new flag "init kubernetes client"
  main.go
Labels: bug, size/S

#187 Refactor flag parsing and logging
  internal/kubernetes/client.go
  main.go
  plugins/metal/plugin.go
Labels: enhancement, size/L, breaking

#189 Use global kubernetes client for `IPAM` plugin
  internal/kubernetes/client.go
  plugins/ipam/k8s.go
Labels: size/S

#188 Add `breaking` labeling to release drafter configuration
  .github/release-drafter.yml
  .github/workflows/lint.yml
  .golangci.yml
  .reuse/dep5
  internal/kubernetes/client.go
  main.go
  plugins/httpboot/plugin.go
  plugins/httpboot/plugin_test.go
  plugins/ipam/k8s.go
  plugins/ipam/plugin.go
  plugins/metal/plugin_test.go
  plugins/onmetal/plugin_test.go
  plugins/oob/k8s.go
  plugins/oob/plugin.go
  plugins/pxeboot/plugin_test.go
Labels: enhancement, size/L

#193 Fix apply endpoint NPE
  plugins/metal/plugin.go
Labels: bug, size/S

#190 Re-enable arm builds
  .github/workflows/publish-docker.yml
  Dockerfile
Labels: enhancement, size/S
