Repository ironcore-dev/FeDHCP, pull requests merged in 2025-01, with the labels that each got.

#234 Switch back to `logrus` for logging
  main.go
  plugins/bluefield/plugin.go
  plugins/ipam/plugin.go
  plugins/metal/plugin.go
  plugins/onmetal/plugin.go
  plugins/oob/plugin.go
  plugins/pxeboot/plugin.go
Labels: enhancement, size/M

#243 Implement new configuration strategy for `httpboot` plugin
  README.md
  config/default/config.yaml
  example/config.yaml
  example/httpboot_config.yaml
  internal/api/httpboot_config.go
  plugins/httpboot/plugin.go
  plugins/httpboot/plugin_test.go
Labels: documentation, enhancement, size/L, breaking

#252 Fix `pxeboot` debug output for IPv6
  plugins/pxeboot/plugin.go
Labels: bug, size/XS

#253 Add tests to `bluefield` plugin
  plugins/bluefield/plugin_test.go
  plugins/bluefield/suite_test.go
Labels: enhancement, size/L
