Repository ironcore-dev/FeDHCP, pull requests merged in 2025-03, with the labels that each got.

#272 Add `REUSE.toml` to reuse list
  REUSE.toml
Labels: chore, size/XS

#274 Update go linter v1.64.5
  Makefile
  plugins/metal/plugin_test.go
Labels: size/XS

#280 Fix unknown plugin for macfilter
  main.go
Labels: bug, size/XS

#281 Remove redundant error messages
  plugins/httpboot/plugin.go
  plugins/oob/plugin.go
  plugins/pxeboot/plugin.go
Labels: size/S

#289 Implement ZTP plugin
  README.md
  example/ztp_config.yaml
  internal/api/ztp_config.go
  main.go
  plugins/ztp/plugin.go
  plugins/ztp/plugin_test.go
  plugins/ztp/suite_test.go
Labels: documentation, enhancement, size/L
